### ISSUE TITLE
New "Fusion Reactor" to negative energy balance

### ISSUE THREAD

**Issue by Dragonseel** [ExileNG/NGSpaceCompany#4] opened 2021-06-23 18:42 UTC
I was casually playing up to trying to get Plasma. I was building my 11x Fusion Reactor and my energy jumped from +600/s to -2k/s
Destroying it returns my +600/s and building it again makes it broken again.

This is a pastebin of my exported save: https://pastebin.com/RnjT9n7p

I am playing on Firefox 81.0,1 (64 bit)

**Comment by Aeraggo** [comment] 2021-06-23 19:19
Looks like the Pastebin isn't available. Just to check though...do you have the Hydrogen/Helium production to support the additional reactor? If you have none stored and underproduce, it generally kills energy production (for example, I've noticed I'll get a tick of negative energy whenever I up the storage for those).

**Comment by Dragonseel** [comment] 2021-06-23 19:32
Hydrogen is at +13.68/s and Helium at +21.66/s according to the left sidebar.

The save again, this time as a github gist. I don't know why the pastbin disappeared. https://gist.github.com/Dragonseel/2e8bedbb8aeaeb01419c162a9c121365

**Comment by Dragonseel** [comment] 2021-06-24 07:15
I just randomly thought about it and found out what the problem was: My Helium storage was very small with 100 units. The 11th Fusion Reactor brought the consumption to >100/s so that in the update tick probably first the reactors try to consume the helium, fail because storage is too small, the energy goes to negative, then the helium producers fill the storage so that in the UI I do not see an empty storage.
I don't know if this is intended behavior, or a bug that needs fixing, but I it was pretty unintuitive for me that the storage is important even if the inflow is big enough for the outflow.

**Comment by ExileNG** [comment] 2021-06-24 11:39
In 1.14.0 version you have some warning that tell you if you need more storage on input resource to produce.
Since it is not a bug, I close it.

**Closed by ExileNG** 2021-06-24 11:39 UTC
